favicon: /images/favicon.ico

menu:
    归档: /archives
    标签: /tags
    相册: /gallery
    关于: /about

article:
    # Show word count and estimated reading time.
    readtime: true
    # Code highlight theme, please see https://highlightjs.org/static/demo/
    highlight: atom-one-dark

logo:
    text: mykonakona

navbar_links:
  RSS:
    icon: fas fa-rss
    url: https://mykonakona.github.io/atom.xml

search:
    type: insight

# Other plugins and their settings.
plugins:
  mathjax: true
  katex: false
  gallery: true
  clipboard: true